#{{- if .Values.ingress.enabled }}
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: springboot-app-ingress
#  annotations:
#    {{- range $key, $value := .Values.ingress.annotations }}
#    {{ $key }}: {{ $value }}
#    {{- end }}
#spec:
#  rules:
#    {{- range .Values.ingress.hosts }}
#    - host: {{ .host }}
#      http:
#        paths:
#          {{- range .paths }}
#          - path: {{ .path }}
#            pathType: {{ .pathType }}
#            backend:
#              service:
#                name: springboot-app
#                port:
#                  number: {{ $.Values.service.port }}
#          {{- end }}
#    {{- end }}
#{{- end }}
